"""Add user_id to mahasiswa

Revision ID: 82f6ada39843
Revises: 
Create Date: 2025-04-21 19:42:38.870286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82f6ada39843'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'mahasiswa', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mahasiswa', type_='foreignkey')
    op.drop_column('mahasiswa', 'user_id')
    # ### end Alembic commands ###
